# Generated by Django 5.2.9 on 2026-04-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_referral_code_user_referral_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shared_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
