# Generated by Django 5.2.9 on 2026-04-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='shared_on_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cv',
            name='shared_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
