# Generated by Django 5.2.9 on 2026-04-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cv_shared_on_social_cv_shared_platforms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='cv',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cv',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.CharField(default='My CV', max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('optimized', 'Optimized'), ('shared', 'Shared')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
